// packages/testground/src/demos/vue/button.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Types &amp; Sizes</div>
      <div class="demo-row">
        <a-button size="small">Small</a-button>
        <a-button>Default</a-button>
        <a-button size="large">Large</a-button>
        <a-button type="primary">Primary</a-button>
        <a-button type="secondary">Secondary</a-button>
        <a-button type="gradient">Gradient</a-button>
        <a-button type="depth">Depth</a-button>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Round &amp; States</div>
      <div class="demo-row">
        <a-button type="primary" round>Round</a-button>
        <a-button type="primary" round anim>Anim</a-button>
        <a-button type="primary" round disabled>Disabled</a-button>
        <a-button type="primary" loading>Loading</a-button>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Icons</div>
      <div class="demo-row">
        <a-button type="primary" icon="eva:alert-circle-fill"></a-button>
        <a-button type="primary" icon="eva:alert-circle-fill" round></a-button>
        <a-button type="primary" icon="eva:alert-circle-fill">Leading</a-button>
        <a-button type="primary" icon="eva:alert-circle-fill" icon-position="trailing"
          >Trailing</a-button
        >
      </div>
    </div>
  </div>
</template>

// packages/testground/src/demos/svelte/button.svelte
<script lang="ts">
  import { Button } from '@any-design/anyui-svelte';
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Types &amp; Sizes</div>
    <div class="demo-row">
      <Button size="small">Small</Button>
      <Button>Default</Button>
      <Button size="large">Large</Button>
      <Button type="primary">Primary</Button>
      <Button type="secondary">Secondary</Button>
      <Button type="gradient">Gradient</Button>
      <Button type="depth">Depth</Button>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Round &amp; States</div>
    <div class="demo-row">
      <Button type="primary" round>Round</Button>
      <Button type="primary" round anim>Anim</Button>
      <Button type="primary" round disabled>Disabled</Button>
      <Button type="primary" loading>Loading</Button>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Icons</div>
    <div class="demo-row">
      <Button type="primary" icon="eva:alert-circle-fill" />
      <Button type="primary" icon="eva:alert-circle-fill" round />
      <Button type="primary" icon="eva:alert-circle-fill">Leading</Button>
      <Button type="primary" icon="eva:alert-circle-fill" iconPosition="trailing">Trailing</Button>
    </div>
  </div>
</div>
