// packages/testground/src/demos/vue/checkbox.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Single</div>
      <div class="demo-row">
        <a-checkbox label="Checkbox"></a-checkbox>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Group</div>
      <div class="demo-row">
        <a-checkbox-group :items="items"></a-checkbox-group>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';

const items = ref(['Option 1', 'Option 2', 'Option 3', 'Option 4', 'Option 5']);
</script>

// packages/testground/src/demos/svelte/checkbox.svelte
<script lang="ts">
  import { Checkbox, CheckboxGroup } from '@any-design/anyui-svelte';

  let checked = $state(true);
  let selected: Array<string | number> = $state(['Option 1']);

  const items = ['Option 1', 'Option 2', 'Option 3'];
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Checkbox</div>
    <div class="demo-row">
      <Checkbox label="Checkbox" bind:modelValue={checked} />
      <span>Checked: {checked}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Checkbox Group</div>
    <div class="demo-col">
      <CheckboxGroup {items} bind:modelValue={selected} />
      <span>Selected: {selected.join(', ') || 'none'}</span>
    </div>
  </div>
</div>
