// packages/testground/src/demos/react/checkbox.tsx
import { useState } from 'react';
import { Checkbox, CheckboxGroup } from '@any-design/anyui-react';

export default function CheckboxDemo() {
  const [checked, setChecked] = useState(false);
  const [groupValue, setGroupValue] = useState<Array<string | number>>(['Option 1']);
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Checkbox</div>
        <div className="demo-row">
          <Checkbox label={`Checkbox (${checked ? 'checked' : 'unchecked'})`} modelValue={checked} onChange={setChecked} />
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Checkbox Group</div>
        <div className="demo-col">
          <CheckboxGroup
            items={['Option 1', 'Option 2', 'Option 3']}
            modelValue={groupValue}
            onUpdateModelValue={setGroupValue}
          />
          <span>Selected: {groupValue.join(', ') || 'none'}</span>
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/svelte/checkbox.svelte
<script lang="ts">
  import { Checkbox, CheckboxGroup } from '@any-design/anyui-svelte';

  let checked = $state(true);
  let selected: Array<string | number> = $state(['Option 1']);

  const items = ['Option 1', 'Option 2', 'Option 3'];
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Checkbox</div>
    <div class="demo-row">
      <Checkbox label="Checkbox" bind:modelValue={checked} />
      <span>Checked: {checked}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Checkbox Group</div>
    <div class="demo-col">
      <CheckboxGroup {items} bind:modelValue={selected} />
      <span>Selected: {selected.join(', ') || 'none'}</span>
    </div>
  </div>
</div>
