// packages/testground/src/demos/react/collapse.tsx
import { useState } from 'react';
import { Button, Collapse } from '@any-design/anyui-react';

export default function CollapseDemo() {
  const [verticalVisible, setVerticalVisible] = useState(false);
  const [horizontalVisible, setHorizontalVisible] = useState(false);
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Vertical</div>
        <div className="demo-col">
          <div className="demo-row">
            <Button onClick={() => setVerticalVisible((value) => !value)}>Toggle Vertical</Button>
          </div>
          <Collapse visible={verticalVisible}>
            {Array.from({ length: 5 }, (_, index) => (
              <p key={index}>vertical content {index + 1}</p>
            ))}
          </Collapse>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Horizontal</div>
        <div className="demo-col">
          <div className="demo-row">
            <Button onClick={() => setHorizontalVisible((value) => !value)}>Toggle Horizontal</Button>
          </div>
          <Collapse direction="horizontal" visible={horizontalVisible}>
            {Array.from({ length: 5 }, (_, index) => (
              <span key={index} style={{ marginRight: 8 }}>
                horizontal
              </span>
            ))}
          </Collapse>
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/svelte/collapse.svelte
<script lang="ts">
  import { Button, Collapse } from '@any-design/anyui-svelte';

  let verticalVisible = $state(false);
  let horizontalVisible = $state(false);
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Vertical</div>
    <div class="demo-col">
      <div class="demo-row">
        <Button size="small" onClick={() => (verticalVisible = !verticalVisible)}>
          Toggle Vertical
        </Button>
      </div>
      <Collapse visible={verticalVisible} alwaysRender>
        <p>Vertical content line 1</p>
        <p>Vertical content line 2</p>
        <p>Vertical content line 3</p>
      </Collapse>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Horizontal</div>
    <div class="demo-col">
      <div class="demo-row">
        <Button size="small" onClick={() => (horizontalVisible = !horizontalVisible)}>
          Toggle Horizontal
        </Button>
      </div>
      <Collapse direction="horizontal" visible={horizontalVisible} alwaysRender>
        <span>horizontal</span>
        <span>horizontal</span>
        <span>horizontal</span>
      </Collapse>
    </div>
  </div>
</div>
