// packages/testground/src/demos/react/empty.tsx
import { Empty } from '@any-design/anyui-react';

export default function EmptyDemo() {
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Default</div>
        <div className="demo-row" style={{ height: 160 }}>
          <Empty text="Not Found" />
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Custom Icon</div>
        <div className="demo-row" style={{ height: 160 }}>
          <Empty icon="iconoir:trash" text="Nothing here" />
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/svelte/empty.svelte
<script lang="ts">
  import { Empty } from '@any-design/anyui-svelte';
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Basic</div>
    <div class="demo-row" style="height: 160px;">
      <Empty text="Not Found" />
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Custom Icon</div>
    <div class="demo-row" style="height: 160px;">
      <Empty icon="iconoir:trash" text="Nothing here" />
    </div>
  </div>
</div>
