// packages/testground/src/demos/vue/form.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Basic</div>
      <div class="demo-row">
        <a-form ref="formRef" v-model="formData" :rules="rules">
          <a-form-item prop="text" label="Label">
            <a-input v-model="formData.text"></a-input>
          </a-form-item>
          <a-form-item>
            <a-button type="primary" @click="submit">Submit</a-button>
          </a-form-item>
        </a-form>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Inline</div>
      <div class="demo-row">
        <a-form ref="inlineFormRef" v-model="inlineFormData" layout="inline" :rules="rules">
          <a-form-item prop="text1" label="Label">
            <a-input v-model="inlineFormData.text1"></a-input>
          </a-form-item>
          <a-form-item prop="text2" label="Label">
            <a-input v-model="inlineFormData.text2"></a-input>
          </a-form-item>
          <a-form-item>
            <a-button type="primary" fill @click="clear">Clear</a-button>
          </a-form-item>
        </a-form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

import type { Form } from '@any-design/anyui-vue';

const formRef = ref<InstanceType<typeof Form>>();
const inlineFormRef = ref<InstanceType<typeof Form>>();

const formData = ref({
  text: '',
});

const inlineFormData = ref({
  text1: '',
  text2: '',
});

const rules = {
  text: [
    {
      required: true,
      message: 'Please input text',
    },
  ],
};

const submit = () => {
  formRef.value?.validate();
};

const clear = () => {
  inlineFormRef.value?.clearFields();
};
</script>

// packages/testground/src/demos/svelte/form.svelte
<script lang="ts">
  import { Button, Form, FormItem, Input } from '@any-design/anyui-svelte';
  import type { FormRuleItem } from '@any-design/anyui-svelte';

  let formRef = $state<{ validate?: () => Promise<boolean>; clearFields?: () => Promise<void> }>();

  const formData: Record<string, unknown> = $state({
    name: '',
    email: '',
  });

  const rules: Record<string, FormRuleItem[]> = {
    name: [{ required: true, message: 'Please input name' }],
    email: [{ required: true, message: 'Please input email', triggerType: 'blur' }],
  };

  let result = $state('');

  const submit = async () => {
    const valid = await formRef?.validate?.();
    result = valid ? 'Form is valid' : 'Form is invalid';
  };

  const clear = () => {
    formRef?.clearFields?.();
    result = '';
  };
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Form with Validation</div>
    <div class="demo-col">
      <Form bind:this={formRef} modelValue={formData} {rules} labelWidth={64}>
        <FormItem prop="name" label="Name">
          <Input placeholder="Validates on change" onChange={(value: string) => (formData.name = value)} />
        </FormItem>
        <FormItem prop="email" label="Email">
          <Input placeholder="Validates on blur" onChange={(value: string) => (formData.email = value)} />
        </FormItem>
        <FormItem>
          <div class="demo-row">
            <Button type="primary" onClick={submit}>Submit</Button>
            <Button onClick={clear}>Clear</Button>
          </div>
        </FormItem>
      </Form>
      {#if result}<span>{result}</span>{/if}
    </div>
  </div>
</div>
