// packages/testground/src/demos/react/gradientText.tsx
import { GradientText } from '@any-design/anyui-react';

export default function GradientTextDemo() {
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Default</div>
        <div className="demo-row">
          <GradientText size="24px">Gradient Text</GradientText>
          <GradientText size="24px" reverseGradient>
            Reversed
          </GradientText>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Custom Gradient</div>
        <div className="demo-row">
          <GradientText size="24px" gradient="linear-gradient(90deg, #ff8a00, #e52e71)">
            Custom Gradient
          </GradientText>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Glow</div>
        <div className="demo-row">
          <GradientText size="24px" glow>
            Glowing Text
          </GradientText>
          <GradientText size="24px" glow reverseGradient>
            Reversed Glow
          </GradientText>
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/svelte/gradientText.svelte
<script lang="ts">
  import { GradientText } from '@any-design/anyui-svelte';
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Basic</div>
    <div class="demo-row">
      <GradientText>Default gradient</GradientText>
      <GradientText reverseGradient>Reversed</GradientText>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Custom</div>
    <div class="demo-row">
      <GradientText gradient="linear-gradient(90deg, #f6d365, #fda085)">
        Custom gradient
      </GradientText>
      <GradientText size={24}>Large text</GradientText>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Glow</div>
    <div class="demo-row">
      <GradientText size={24} glow>Glowing text</GradientText>
      <GradientText size={24} glow reverseGradient>Reversed glow</GradientText>
    </div>
  </div>
</div>
