// packages/testground/src/demos/react/input.tsx
import { useState } from 'react';
import { Button, Input } from '@any-design/anyui-react';

export default function InputDemo() {
  const [value, setValue] = useState('');
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Basic</div>
        <div className="demo-col">
          <Input placeholder="Default" />
          <Input placeholder="Round" round />
          <Input placeholder="Large" size="large" />
          <Input placeholder="Borderless" borderless />
          <Input placeholder="Disabled" disabled />
          <Input modelValue="This is a read only input" readonly />
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Prefix &amp; Post Button</div>
        <div className="demo-col">
          <Input placeholder="With prefix" prefix={<span>@</span>} />
          <Input placeholder="With postfix" postfix={<span>.com</span>} />
          <Input placeholder="With post button" postButton={<Button size="small" type="gradient">Submit</Button>} />
          <Input
            placeholder="With rounded post button"
            borderless
            round
            postButton={
              <Button type="gradient" size="small" round>
                Search
              </Button>
            }
          />
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Controlled</div>
        <div className="demo-col">
          <Input placeholder="Type something..." modelValue={value} onUpdateModelValue={setValue} />
          <span>Value: {value || '(empty)'}</span>
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/svelte/input.svelte
<script lang="ts">
  import { Button, Input } from '@any-design/anyui-svelte';

  let text = $state('');

  const onInput = (event: Event) => {
    const target = event.target as HTMLInputElement | null;
    text = target ? target.value : '';
  };
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Variants</div>
    <div class="demo-col">
      <Input placeholder="Default" />
      <Input placeholder="Round" round />
      <Input placeholder="Large" size="large" />
      <Input placeholder="Borderless" borderless />
      <Input placeholder="Disabled" disabled />
      <Input modelValue="This is a read only input" readonly />
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Prefix &amp; Postfix</div>
    <div class="demo-col">
      <Input placeholder="With prefix" prefix="@" />
      <Input placeholder="With postfix" postfix="kg" />
      <Input placeholder="With post button">
        {#snippet postButton()}
          <Button type="gradient" size="small">Submit</Button>
        {/snippet}
      </Input>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Events</div>
    <div class="demo-col">
      <Input placeholder="Type something..." {onInput} />
      <span>Value: {text || '(empty)'}</span>
    </div>
  </div>
</div>
