// packages/testground/src/demos/react/listMenu.tsx
import { useState } from 'react';
import { ListMenu } from '@any-design/anyui-react';

const menu = {
  Accounts: ['My Account'],
  UI: ['Theme'],
  Security: ['Storage', 'API'],
};

export default function ListMenuDemo() {
  const [selected, setSelected] = useState<string | undefined>('Theme');
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Grouped Menu</div>
        <div className="demo-row">
          <div style={{ width: 180 }}>
            <ListMenu menu={menu} modelValue={selected} onUpdateModelValue={setSelected} />
          </div>
          <span>Selected: {selected ?? 'none'}</span>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Flat Menu</div>
        <div className="demo-row">
          <div style={{ width: 180 }}>
            <ListMenu menu={['Home', 'Profile', 'Settings']} />
          </div>
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/svelte/listMenu.svelte
<script lang="ts">
  import { ListMenu } from '@any-design/anyui-svelte';
  import type { AListMenuConfig } from '@any-design/anyui-svelte';

  const menu: AListMenuConfig = {
    Accounts: ['My Account'],
    UI: ['Theme'],
    Security: ['Storage', 'API'],
  };

  let selected: string | undefined = $state('Theme');
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">List Menu</div>
    <div class="demo-row">
      <div style="width: 180px;">
        <ListMenu {menu} bind:modelValue={selected} />
      </div>
      <span>Selected: {selected ?? 'none'}</span>
    </div>
  </div>
</div>
