// packages/testground/src/demos/react/loadingMask.tsx
import { useState } from 'react';
import { Button, Card, LoadingMask, loadingMask } from '@any-design/anyui-react';

export default function LoadingMaskDemo() {
  const [cardLoading, setCardLoading] = useState(false);

  const showFullscreen = () => {
    loadingMask.show({ text: 'Hold on...' });
    setTimeout(() => {
      loadingMask.hide();
    }, 2000);
  };

  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Wrap content</div>
        <div className="demo-row">
          <LoadingMask loading={cardLoading} text="Loading...">
            <Card title="Project stats" width={280}>
              <p style={{ margin: 0 }}>Stars: 1,024</p>
              <p style={{ margin: '6px 0 0' }}>Forks: 256</p>
            </Card>
          </LoadingMask>
          <Button type="primary" onClick={() => setCardLoading((loading) => !loading)}>
            {cardLoading ? 'Stop' : 'Start'} loading
          </Button>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Fullscreen helper</div>
        <div className="demo-row">
          <Button onClick={showFullscreen}>Show fullscreen for 2s</Button>
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/svelte/loadingMask.svelte
<script lang="ts">
  import { Button, Card, LoadingMask, loadingMask } from '@any-design/anyui-svelte';

  let cardLoading = $state(false);

  const showFullscreen = () => {
    loadingMask.show({ text: 'Hold on...' });
    setTimeout(() => {
      loadingMask.hide();
    }, 2000);
  };
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Wrap content</div>
    <div class="demo-row">
      <LoadingMask loading={cardLoading} text="Loading...">
        <Card title="Project stats" width={280}>
          <p style="margin: 0;">Stars: 1,024</p>
          <p style="margin: 6px 0 0;">Forks: 256</p>
        </Card>
      </LoadingMask>
      <Button type="primary" onClick={() => (cardLoading = !cardLoading)}>
        {cardLoading ? 'Stop' : 'Start'} loading
      </Button>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Fullscreen helper</div>
    <div class="demo-row">
      <Button onClick={showFullscreen}>Show fullscreen for 2s</Button>
    </div>
  </div>
</div>
