// packages/testground/src/demos/react/masonry.tsx
import type { CSSProperties } from 'react';

import { Masonry } from '@any-design/anyui-react';

interface DemoItem {
  id: string;
  height: number;
}

const items: DemoItem[] = Array.from({ length: 12 }, (_, index) => ({
  id: `item_${index}`,
  height: Math.floor((Math.sin(index * 7) + 1) * 60) + 60,
}));

const itemHeightGetter = (item: DemoItem) => item.height;

const cardStyle: CSSProperties = {
  width: '100%',
  height: '100%',
  borderRadius: 12,
  background: 'var(--primary)',
  color: 'var(--text-btn)',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
};

export default function MasonryDemo() {
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Fit Columns</div>
        <Masonry items={items} itemHeightGetter={itemHeightGetter} colWidth={110} gap={12} fit>
          {(item: DemoItem, index: number) => <div style={cardStyle}>{index}</div>}
        </Masonry>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Fixed 2 Columns</div>
        <Masonry items={items} itemHeightGetter={itemHeightGetter} col={2} colWidth={140} gap={12}>
          {(item: DemoItem, index: number) => <div style={cardStyle}>{index}</div>}
        </Masonry>
      </div>
    </div>
  );
}

// packages/testground/src/demos/svelte/masonry.svelte
<script lang="ts">
  import { Masonry } from '@any-design/anyui-svelte';
  import type { MasonryItem } from '@any-design/anyui-svelte';

  const items: MasonryItem[] = Array.from({ length: 12 }, (_, index) => ({
    id: index,
    height: 48 + (index % 4) * 28,
  }));

  const itemHeightGetter = (item: MasonryItem) => Number(item.height);
</script>

<div class="masonry-demo">
  <div class="demo-block">
    <div class="demo-block__label">Fit Columns</div>
    <Masonry {items} {itemHeightGetter} colWidth={110} gap={12} fit>
      {#snippet children(item, index)}
        <div class="masonry-card">{index}</div>
      {/snippet}
    </Masonry>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Fixed 2 Columns</div>
    <Masonry {items} {itemHeightGetter} col={2} colWidth={140} gap={12}>
      {#snippet children(item, index)}
        <div class="masonry-card">{index}</div>
      {/snippet}
    </Masonry>
  </div>
</div>

<style>
  .masonry-card {
    width: 100%;
    height: 100%;
    border-radius: 12px;
    background: var(--primary, #7388e6);
    color: var(--text-btn, #fff);
    display: flex;
    align-items: center;
    justify-content: center;
  }
</style>
