// packages/testground/src/demos/react/otpInput.tsx
import { useState } from 'react';
import { OtpInput } from '@any-design/anyui-react';

export default function OtpInputDemo() {
  const [code, setCode] = useState('');
  const [completed, setCompleted] = useState('');
  const [pin, setPin] = useState('');
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">6-digit Code</div>
        <div className="demo-col">
          <OtpInput modelValue={code} onUpdateModelValue={setCode} onComplete={setCompleted} />
          <span>Value: {code || 'empty'}</span>
          <span>Completed: {completed || 'not yet'}</span>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">4-digit Masked</div>
        <div className="demo-col">
          <OtpInput modelValue={pin} length={4} masked onUpdateModelValue={setPin} />
          <span>Value: {pin || 'empty'}</span>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Sizes</div>
        <div className="demo-row">
          <OtpInput modelValue="12" length={4} size="small" />
          <OtpInput modelValue="123" length={4} />
          <OtpInput modelValue="1234" length={4} size="large" />
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Disabled</div>
        <div className="demo-row">
          <OtpInput modelValue="12" length={4} disabled />
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/svelte/otpInput.svelte
<script lang="ts">
  import { OtpInput } from '@any-design/anyui-svelte';

  let code = $state('');
  let completed = $state('');
  let pin = $state('');
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">6-digit Code</div>
    <div class="demo-col">
      <OtpInput bind:modelValue={code} onComplete={(value) => (completed = value)} />
      <span>Value: {code || 'empty'}</span>
      <span>Completed: {completed || 'not yet'}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">4-digit Masked</div>
    <div class="demo-col">
      <OtpInput bind:modelValue={pin} length={4} masked />
      <span>Value: {pin || 'empty'}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Sizes</div>
    <div class="demo-row">
      <OtpInput modelValue="12" length={4} size="small" />
      <OtpInput modelValue="123" length={4} />
      <OtpInput modelValue="1234" length={4} size="large" />
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Disabled</div>
    <div class="demo-row">
      <OtpInput modelValue="12" length={4} disabled />
    </div>
  </div>
</div>
