// packages/testground/src/demos/vue/pagination.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Variants</div>
      <div class="demo-col">
        <a-pagination v-model:pagination="pagination_1"></a-pagination>
        <a-pagination v-model:pagination="pagination_2" :boundary-count="2"></a-pagination>
        <a-pagination v-model:pagination="pagination_3" :sibling-count="2"></a-pagination>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Shapes</div>
      <div class="demo-col">
        <a-pagination v-model:pagination="pagination_shapes" shape="rounded"></a-pagination>
        <a-pagination v-model:pagination="pagination_shapes" shape="squircle"></a-pagination>
        <a-pagination v-model:pagination="pagination_shapes" shape="circle"></a-pagination>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const pagination_1 = ref({
  current: 1,
  pageSize: 10,
  total: 100,
});

const pagination_2 = ref({
  current: 1,
  pageSize: 10,
  total: 100,
});

const pagination_3 = ref({
  current: 1,
  pageSize: 10,
  total: 150,
});

const pagination_shapes = ref({
  current: 3,
  pageSize: 10,
  total: 200,
});
</script>

// packages/testground/src/demos/svelte/pagination.svelte
<script lang="ts">
  import { Pagination } from '@any-design/anyui-svelte';
  import type { PaginationMeta } from '@any-design/anyui-svelte';

  let pagination: PaginationMeta = $state({ current: 1, pageSize: 10, total: 50 });
  let largePagination: PaginationMeta = $state({ current: 3, pageSize: 10, total: 80 });
  let shapesPagination: PaginationMeta = $state({ current: 3, pageSize: 10, total: 200 });
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Basic</div>
    <div class="demo-col">
      <Pagination bind:pagination />
      <span>Current page: {pagination.current}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">More Pages</div>
    <div class="demo-col">
      <Pagination bind:pagination={largePagination} />
      <span>Current page: {largePagination.current}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Shapes</div>
    <div class="demo-col">
      <Pagination bind:pagination={shapesPagination} shape="rounded" />
      <Pagination bind:pagination={shapesPagination} shape="squircle" />
      <Pagination bind:pagination={shapesPagination} shape="circle" />
    </div>
  </div>
</div>
