// packages/testground/src/demos/vue/popupMenu.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Triggers</div>
      <div class="demo-row">
        <a-popup-menu :items="items" @command="handleCommand">
          <span>trigger (hover)</span>
        </a-popup-menu>
        <a-popup-menu :items="items" triggerType="click">
          <span>trigger (click)</span>
        </a-popup-menu>
        <a-popup-menu :items="items" :appendToBody="false">
          <span>trigger (inset)</span>
        </a-popup-menu>
        <a-popup-menu :items="items" triggerType="click" hideAfterClick>
          <span>trigger (click &amp; hideAfterClick)</span>
        </a-popup-menu>
        <a-popup-menu :items="items" triggerType="contextmenu" hideAfterClick>
          <span>trigger (contextmenu)</span>
        </a-popup-menu>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Grouped</div>
      <div class="demo-row">
        <a-popup-menu group="test" :items="items" triggerType="click" hideAfterClick>
          <span>trigger (click) (grouped)</span>
        </a-popup-menu>
        <a-popup-menu group="test" :items="items" triggerType="contextmenu" hideAfterClick>
          <span>trigger (contextmenu) (grouped)</span>
        </a-popup-menu>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { PopMenuCommandExtra } from '@/packages/popupMenu/types';

const items = ['Item 1', 'Item 2', 'Item 3', 'Item 4'];

const handleCommand = (command: string, extra: PopMenuCommandExtra) => {
  console.log('command', command, 'extra', extra);
};
</script>

// packages/testground/src/demos/svelte/popupMenu.svelte
<script lang="ts">
  import { PopupMenu } from '@any-design/anyui-svelte';

  const items = ['Item 1', 'Item 2', 'Item 3', 'Item 4'];

  let lastCommand = $state('');

  const onCommand = (command: string) => {
    lastCommand = command;
  };
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Trigger Types</div>
    <div class="demo-row">
      <PopupMenu {items} {onCommand}>
        <span class="popup-menu-trigger">hover</span>
      </PopupMenu>
      <PopupMenu {items} triggerType="click" hideAfterClick {onCommand}>
        <span class="popup-menu-trigger">click</span>
      </PopupMenu>
      <PopupMenu {items} triggerType="contextmenu" hideAfterClick {onCommand}>
        <span class="popup-menu-trigger">contextmenu</span>
      </PopupMenu>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Grouped (only one opens)</div>
    <div class="demo-row">
      <PopupMenu {items} group="demo" triggerType="click" hideAfterClick {onCommand}>
        <span class="popup-menu-trigger">grouped A</span>
      </PopupMenu>
      <PopupMenu {items} group="demo" triggerType="click" hideAfterClick {onCommand}>
        <span class="popup-menu-trigger">grouped B</span>
      </PopupMenu>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Command Event</div>
    <div class="demo-row">
      <span>Last command: {lastCommand || 'none'}</span>
    </div>
  </div>
</div>

<style>
  .popup-menu-trigger {
    cursor: pointer;
    text-decoration: underline;
  }
</style>
