// packages/testground/src/demos/react/popup.tsx
import { useState } from 'react';
import { Button, Popup } from '@any-design/anyui-react';

export default function PopupDemo() {
  const [basicVisible, setBasicVisible] = useState(false);
  const [lockedVisible, setLockedVisible] = useState(false);
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Basic</div>
        <div className="demo-row">
          <Button type="primary" onClick={() => setBasicVisible(true)}>
            Open popup
          </Button>
          <Popup modelValue={basicVisible} width={360} onUpdateModelValue={setBasicVisible}>
            <div style={{ padding: 24 }}>
              <p style={{ margin: '0 0 16px' }}>A bare popup panel, close by mask or Esc.</p>
              <Button size="small" onClick={() => setBasicVisible(false)}>
                Close
              </Button>
            </div>
          </Popup>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Not mask closable</div>
        <div className="demo-row">
          <Button onClick={() => setLockedVisible(true)}>Open popup</Button>
          <Popup
            modelValue={lockedVisible}
            width={360}
            maskClosable={false}
            onUpdateModelValue={setLockedVisible}
          >
            <div style={{ padding: 24 }}>
              <p style={{ margin: '0 0 16px' }}>Mask click and Esc are disabled here.</p>
              <Button size="small" type="primary" onClick={() => setLockedVisible(false)}>
                Close
              </Button>
            </div>
          </Popup>
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/svelte/popup.svelte
<script lang="ts">
  import { Button, Popup } from '@any-design/anyui-svelte';

  let basicVisible = $state(false);
  let lockedVisible = $state(false);
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Basic</div>
    <div class="demo-row">
      <Button type="primary" onClick={() => (basicVisible = true)}>Open popup</Button>
      <Popup bind:modelValue={basicVisible} width={360}>
        <div style="padding: 24px;">
          <p style="margin: 0 0 16px;">A bare popup panel, close by mask or Esc.</p>
          <Button size="small" onClick={() => (basicVisible = false)}>Close</Button>
        </div>
      </Popup>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Not mask closable</div>
    <div class="demo-row">
      <Button onClick={() => (lockedVisible = true)}>Open popup</Button>
      <Popup bind:modelValue={lockedVisible} width={360} maskClosable={false}>
        <div style="padding: 24px;">
          <p style="margin: 0 0 16px;">Mask click and Esc are disabled here.</p>
          <Button size="small" type="primary" onClick={() => (lockedVisible = false)}>Close</Button>
        </div>
      </Popup>
    </div>
  </div>
</div>
