// packages/testground/src/demos/vue/scrollArea.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Fixed Height</div>
      <div class="demo-row">
        <a-scroll-area :height="220" scroll-fade class="scroll-demo">
          <div v-for="row in rows" :key="row" class="scroll-demo__row">Row {{ row }}</div>
        </a-scroll-area>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Horizontal</div>
      <div class="demo-row">
        <a-scroll-area
          :height="80"
          horizontal
          :scroll-fade="{ size: 28, reveal: 72 }"
          class="scroll-demo scroll-demo--wide"
        >
          <div class="scroll-demo__strip">
            <div v-for="col in 24" :key="col" class="scroll-demo__chip">Item {{ col }}</div>
          </div>
        </a-scroll-area>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">ScrollFade Wrapper</div>
      <div class="demo-row">
        <a-scroll-fade height="160" size="36" class="scroll-demo">
          <div v-for="row in rows" :key="`fade-${row}`" class="scroll-demo__row">
            Fade row {{ row }}
          </div>
        </a-scroll-fade>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
const rows = Array.from({ length: 30 }, (_, index) => index + 1);
</script>

<style scoped>
.scroll-demo {
  width: 320px;
  border: 1px solid var(--border);
  border-radius: var(--a-radius, 14px);
  background: var(--a-surface, var(--bg-bright));
}

.scroll-demo--wide {
  width: 420px;
}

.scroll-demo__row {
  padding: 10px 16px;
  border-bottom: 1px solid var(--line);
}

.scroll-demo__strip {
  display: flex;
  gap: 8px;
  padding: 16px;
}

.scroll-demo__chip {
  flex-shrink: 0;
  padding: 8px 16px;
  border-radius: var(--a-radius-full, 999px);
  background: var(--bg-semi-dark);
  white-space: nowrap;
}
</style>

// packages/testground/src/demos/svelte/scrollArea.svelte
<script lang="ts">
  import { ScrollArea, ScrollFade } from '@any-design/anyui-svelte';

  const rows = Array.from({ length: 30 }, (_, index) => index + 1);
  const cols = Array.from({ length: 24 }, (_, index) => index + 1);
  const fadeOptions = { size: 28, reveal: 72 };
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Fixed Height</div>
    <div class="demo-row">
      <ScrollArea height={220} scrollFade class="scroll-demo">
        {#each rows as row (row)}
          <div class="scroll-demo__row">Row {row}</div>
        {/each}
      </ScrollArea>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Horizontal</div>
    <div class="demo-row">
      <ScrollArea height={80} horizontal scrollFade={fadeOptions} class="scroll-demo scroll-demo--wide">
        <div class="scroll-demo__strip">
          {#each cols as col (col)}
            <div class="scroll-demo__chip">Item {col}</div>
          {/each}
        </div>
      </ScrollArea>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">ScrollFade Wrapper</div>
    <div class="demo-row">
      <ScrollFade height={160} size={36} class="scroll-demo">
        {#each rows as row (row)}
          <div class="scroll-demo__row">Fade row {row}</div>
        {/each}
      </ScrollFade>
    </div>
  </div>
</div>

<style>
  :global(.scroll-demo) {
    width: 320px;
    border: 1px solid var(--border);
    border-radius: var(--a-radius, 14px);
    background: var(--a-surface, var(--bg-bright));
  }

  :global(.scroll-demo--wide) {
    width: 420px;
  }

  .scroll-demo__row {
    padding: 10px 16px;
    border-bottom: 1px solid var(--line);
  }

  .scroll-demo__strip {
    display: flex;
    gap: 8px;
    padding: 16px;
  }

  .scroll-demo__chip {
    flex-shrink: 0;
    padding: 8px 16px;
    border-radius: var(--a-radius-full, 999px);
    background: var(--bg-semi-dark);
    white-space: nowrap;
  }
</style>
