// packages/testground/src/demos/react/scrollArea.tsx
import type { CSSProperties } from 'react';
import { ScrollArea, ScrollFade } from '@any-design/anyui-react';

const rows = Array.from({ length: 30 }, (_, index) => index + 1);

const boxStyle: CSSProperties = {
  width: 320,
  border: '1px solid var(--border)',
  borderRadius: 'var(--a-radius, 14px)',
  background: 'var(--a-surface, var(--bg-bright))',
};

const rowStyle: CSSProperties = {
  padding: '10px 16px',
  borderBottom: '1px solid var(--line)',
};

const stripStyle: CSSProperties = {
  display: 'flex',
  gap: 8,
  padding: 16,
};

const chipStyle: CSSProperties = {
  flexShrink: 0,
  padding: '8px 16px',
  borderRadius: 'var(--a-radius-full, 999px)',
  background: 'var(--bg-semi-dark)',
  whiteSpace: 'nowrap',
};

export default function ScrollAreaDemo() {
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Fixed Height</div>
        <div className="demo-row">
          <ScrollArea height={220} scrollFade style={boxStyle}>
            {rows.map((row) => (
              <div key={row} style={rowStyle}>
                Row {row}
              </div>
            ))}
          </ScrollArea>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Horizontal</div>
        <div className="demo-row">
          <ScrollArea height={80} horizontal scrollFade={{ size: 28, reveal: 72 }} style={{ ...boxStyle, width: 420 }}>
            <div style={stripStyle}>
              {Array.from({ length: 24 }, (_, index) => (
                <div key={index} style={chipStyle}>
                  Item {index + 1}
                </div>
              ))}
            </div>
          </ScrollArea>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">ScrollFade Wrapper</div>
        <div className="demo-row">
          <ScrollFade height={160} size={36} style={boxStyle}>
            {rows.map((row) => (
              <div key={`fade-${row}`} style={rowStyle}>
                Fade row {row}
              </div>
            ))}
          </ScrollFade>
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/svelte/scrollArea.svelte
<script lang="ts">
  import { ScrollArea, ScrollFade } from '@any-design/anyui-svelte';

  const rows = Array.from({ length: 30 }, (_, index) => index + 1);
  const cols = Array.from({ length: 24 }, (_, index) => index + 1);
  const fadeOptions = { size: 28, reveal: 72 };
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Fixed Height</div>
    <div class="demo-row">
      <ScrollArea height={220} scrollFade class="scroll-demo">
        {#each rows as row (row)}
          <div class="scroll-demo__row">Row {row}</div>
        {/each}
      </ScrollArea>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Horizontal</div>
    <div class="demo-row">
      <ScrollArea height={80} horizontal scrollFade={fadeOptions} class="scroll-demo scroll-demo--wide">
        <div class="scroll-demo__strip">
          {#each cols as col (col)}
            <div class="scroll-demo__chip">Item {col}</div>
          {/each}
        </div>
      </ScrollArea>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">ScrollFade Wrapper</div>
    <div class="demo-row">
      <ScrollFade height={160} size={36} class="scroll-demo">
        {#each rows as row (row)}
          <div class="scroll-demo__row">Fade row {row}</div>
        {/each}
      </ScrollFade>
    </div>
  </div>
</div>

<style>
  :global(.scroll-demo) {
    width: 320px;
    border: 1px solid var(--border);
    border-radius: var(--a-radius, 14px);
    background: var(--a-surface, var(--bg-bright));
  }

  :global(.scroll-demo--wide) {
    width: 420px;
  }

  .scroll-demo__row {
    padding: 10px 16px;
    border-bottom: 1px solid var(--line);
  }

  .scroll-demo__strip {
    display: flex;
    gap: 8px;
    padding: 16px;
  }

  .scroll-demo__chip {
    flex-shrink: 0;
    padding: 8px 16px;
    border-radius: var(--a-radius-full, 999px);
    background: var(--bg-semi-dark);
    white-space: nowrap;
  }
</style>
