// packages/testground/src/demos/react/select.tsx
import { useState } from 'react';
import { Select } from '@any-design/anyui-react';
import type { ASelectItems } from '@any-design/anyui-react';

const items: ASelectItems = Array.from({ length: 6 }, (_, index) => ({
  text: `Item ${index}`,
  value: index,
}));

export default function SelectDemo() {
  const [value, setValue] = useState<string | number>('');
  const [multiValue, setMultiValue] = useState<(string | number)[]>([]);
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Basic</div>
        <div className="demo-col">
          <Select items={items} placeholder="Select an item" modelValue={value} onUpdateModelValue={setValue} />
          <span>Selected: {value === '' ? '(none)' : value}</span>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Multiple</div>
        <div className="demo-col">
          <Select items={items} placeholder="Select items" multiple modelValue={multiValue} onUpdateModelValue={setMultiValue} />
          <span>Selected: {multiValue.length ? multiValue.join(', ') : '(none)'}</span>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Variants</div>
        <div className="demo-col">
          <Select items={items} placeholder="Round" round />
          <Select items={items} placeholder="Large" size="large" />
          <Select items={items} placeholder="Disabled" disabled />
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/svelte/select.svelte
<script lang="ts">
  import { Select } from '@any-design/anyui-svelte';
  import type { ASelectItems } from '@any-design/anyui-svelte';

  const items: ASelectItems = Array.from({ length: 6 }, (_, index) => ({
    text: `Item ${index}`,
    value: index,
  }));

  let value: string | number | null | undefined = $state('');
  let multiValue: (string | number)[] = $state([]);
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Basic</div>
    <div class="demo-col">
      <Select {items} bind:modelValue={value} placeholder="Select an item" />
      <span>Selected: {value === '' ? '(none)' : value}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Multiple</div>
    <div class="demo-col">
      <Select {items} bind:modelValue={multiValue} multiple placeholder="Select items" />
      <span>Selected: {multiValue.length ? multiValue.join(', ') : '(none)'}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Variants</div>
    <div class="demo-col">
      <Select {items} round placeholder="Round" />
      <Select {items} size="large" placeholder="Large" />
      <Select {items} disabled placeholder="Disabled" />
    </div>
  </div>
</div>
