// packages/testground/src/demos/vue/switch.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Switch</div>
      <div class="demo-row">
        <a-switch v-model="enabled"></a-switch>
        <span>Enabled: {{ enabled }}</span>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Disabled</div>
      <div class="demo-row">
        <a-switch :model-value="true" disabled></a-switch>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue';

const enabled = ref(true);
</script>

// packages/testground/src/demos/svelte/switch.svelte
<script lang="ts">
  import { Switch } from '@any-design/anyui-svelte';

  let enabled = $state(true);
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Switch</div>
    <div class="demo-row">
      <Switch bind:modelValue={enabled} />
      <span>Enabled: {enabled}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Disabled</div>
    <div class="demo-row">
      <Switch modelValue={true} disabled />
    </div>
  </div>
</div>
