// packages/testground/src/demos/vue/tag.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Sizes</div>
      <div class="demo-row">
        <a-tag size="small">small</a-tag>
        <a-tag>default</a-tag>
        <a-tag size="large">large</a-tag>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Round &amp; Custom Color</div>
      <div class="demo-row">
        <a-tag round>round</a-tag>
        <a-tag color="#1faeff">custom color</a-tag>
        <a-tag round color="#e52e71" bgColor="#ffe2ec">custom bg</a-tag>
      </div>
    </div>
  </div>
</template>

// packages/testground/src/demos/svelte/tag.svelte
<script lang="ts">
  import { Tag } from '@any-design/anyui-svelte';
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Sizes</div>
    <div class="demo-row">
      <Tag size="small">small</Tag>
      <Tag>default</Tag>
      <Tag size="large">large</Tag>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Round &amp; Custom Color</div>
    <div class="demo-row">
      <Tag round>round</Tag>
      <Tag color="#1faeff">custom color</Tag>
      <Tag round color="#e52e71" bgColor="#ffe2ec">custom bg</Tag>
    </div>
  </div>
</div>
