// packages/testground/src/demos/react/tag.tsx
import { Tag } from '@any-design/anyui-react';

export default function TagDemo() {
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Sizes</div>
        <div className="demo-row">
          <Tag size="small">small</Tag>
          <Tag>default</Tag>
          <Tag size="large">large</Tag>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Round &amp; Custom Color</div>
        <div className="demo-row">
          <Tag round>round</Tag>
          <Tag color="#1faeff">custom color</Tag>
          <Tag bgColor="#ffe2ec" color="#e52e71" round>
            custom bg
          </Tag>
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/svelte/tag.svelte
<script lang="ts">
  import { Tag } from '@any-design/anyui-svelte';
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Sizes</div>
    <div class="demo-row">
      <Tag size="small">small</Tag>
      <Tag>default</Tag>
      <Tag size="large">large</Tag>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Round &amp; Custom Color</div>
    <div class="demo-row">
      <Tag round>round</Tag>
      <Tag color="#1faeff">custom color</Tag>
      <Tag round color="#e52e71" bgColor="#ffe2ec">custom bg</Tag>
    </div>
  </div>
</div>
