// packages/testground/src/demos/svelte/avatar.svelte
<script lang="ts">
  import { Avatar } from '@any-design/anyui-svelte';

  const src = 'https://0.gravatar.com/avatar/';
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Sizes</div>
    <div class="demo-row">
      <Avatar {src} size="xlarge" />
      <Avatar {src} size="large" />
      <Avatar {src} size="medium" />
      <Avatar {src} size="small" />
      <Avatar {src} size="xsmall" />
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Round &amp; Custom Width</div>
    <div class="demo-row">
      <Avatar {src} size="large" round />
      <Avatar {src} width={40} />
      <Avatar {src} width="56px" round />
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Fallback</div>
    <div class="demo-row">
      <Avatar size="large" round>AU</Avatar>
      <Avatar size="large" fallback="A" />
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Name initials fallback</div>
    <div class="demo-row">
      <Avatar src="" name="Ada Lovelace" size="large" round />
      <Avatar src="" name="Turing" size="large" />
      <Avatar src="" name="宮崎駿" size="large" round />
      <Avatar src="https://broken.example/missing.png" name="Grace Hopper" width={40} round />
      <Avatar src="" name="Linus Torvalds" size="small" round />
    </div>
  </div>
</div>

// packages/testground/src/demos/vue/avatar.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Sizes &amp; Shapes</div>
      <div class="demo-row">
        <a-avatar src="https://0.gravatar.com/avatar/" :size="AvatarSize.Large" round />
        <a-avatar src="https://0.gravatar.com/avatar/" :size="AvatarSize.Medium" />
        <a-avatar src="https://0.gravatar.com/avatar/" :width="40" />
        <a-avatar src="https://0.gravatar.com/avatar/" width="50px" round />
        <a-avatar src="https://0.gravatar.com/avatar/" :size="AvatarSize.XSmall" />
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Name initials fallback</div>
      <div class="demo-row">
        <a-avatar src="" name="Ada Lovelace" :size="AvatarSize.Large" round />
        <a-avatar src="" name="Turing" :size="AvatarSize.Large" />
        <a-avatar src="" name="宮崎駿" :size="AvatarSize.Large" round />
        <a-avatar src="https://broken.example/missing.png" name="Grace Hopper" :width="40" round />
        <a-avatar src="" name="Linus Torvalds" :size="AvatarSize.Small" round />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { AvatarSize } from '@/packages/avatar';
</script>
