// packages/testground/src/demos/react/clickableText.tsx
import { ClickableText } from '@any-design/anyui-react';

export default function ClickableTextDemo() {
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Types</div>
        <div className="demo-row">
          <ClickableText onClick={() => console.log('clicked default')}>Default</ClickableText>
          <ClickableText type="primary" onClick={() => console.log('clicked primary')}>
            Primary
          </ClickableText>
          <ClickableText type="secondary" onClick={() => console.log('clicked secondary')}>
            Secondary
          </ClickableText>
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/vue/clickableText.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Types</div>
      <div class="demo-row">
        <a-clickable-text>Default</a-clickable-text>
        <a-clickable-text type="primary">Primary</a-clickable-text>
        <a-clickable-text type="secondary">Secondary</a-clickable-text>
      </div>
    </div>
  </div>
</template>
