// packages/testground/src/demos/react/collapse.tsx
import { useState } from 'react';
import { Button, Collapse } from '@any-design/anyui-react';

export default function CollapseDemo() {
  const [verticalVisible, setVerticalVisible] = useState(false);
  const [horizontalVisible, setHorizontalVisible] = useState(false);
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Vertical</div>
        <div className="demo-col">
          <div className="demo-row">
            <Button onClick={() => setVerticalVisible((value) => !value)}>Toggle Vertical</Button>
          </div>
          <Collapse visible={verticalVisible}>
            {Array.from({ length: 5 }, (_, index) => (
              <p key={index}>vertical content {index + 1}</p>
            ))}
          </Collapse>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Horizontal</div>
        <div className="demo-col">
          <div className="demo-row">
            <Button onClick={() => setHorizontalVisible((value) => !value)}>Toggle Horizontal</Button>
          </div>
          <Collapse direction="horizontal" visible={horizontalVisible}>
            {Array.from({ length: 5 }, (_, index) => (
              <span key={index} style={{ marginRight: 8 }}>
                horizontal
              </span>
            ))}
          </Collapse>
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/vue/collapse.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Vertical</div>
      <div class="demo-row">
        <a-button @click="verticalVisible = !verticalVisible">Toggle</a-button>
        <a-collapse :visible="verticalVisible">
          <p v-for="(_, idx) in new Array(4).fill(0)" :key="idx">vertical</p>
        </a-collapse>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Horizontal</div>
      <div class="demo-row">
        <a-button @click="horizontalVisible = !horizontalVisible">Toggle</a-button>
        <a-collapse direction="horizontal" :visible="horizontalVisible">
          <span v-for="(_, idx) in new Array(4).fill(0)" :key="idx">horizontal&nbsp;</span>
        </a-collapse>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const verticalVisible = ref(false);
const horizontalVisible = ref(false);
</script>
