// packages/testground/src/demos/svelte/drawer.svelte
<script lang="ts">
  import { Button, Drawer } from '@any-design/anyui-svelte';

  let visible = $state(false);
  let position = $state('left');

  const openDrawer = (nextPosition: string) => {
    position = nextPosition;
    visible = true;
  };
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Positions</div>
    <div class="demo-row">
      <Button type="primary" onClick={() => openDrawer('left')}>Left</Button>
      <Button type="primary" onClick={() => openDrawer('right')}>Right</Button>
    </div>
  </div>
  <Drawer bind:modelValue={visible} {position} width={240}>
    <div style="padding: 24px;">
      <p>This is a drawer.</p>
      <Button size="small" onClick={() => (visible = false)}>Close</Button>
    </div>
  </Drawer>
</div>

// packages/testground/src/demos/vue/drawer.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Positions</div>
      <div class="demo-row">
        <a-button type="primary" @click="openDrawer('left')">Left</a-button>
        <a-button type="primary" @click="openDrawer('right')">Right</a-button>
        <a-drawer v-model="drawerVisible" :position="drawerPosition" appendToBody>
          <span>This is a drawer</span>
        </a-drawer>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

import type { DrawerPosition } from '@/packages/drawer';

const drawerPosition = ref<DrawerPosition>('left');
const drawerVisible = ref(false);

const openDrawer = (position: DrawerPosition) => {
  drawerPosition.value = position;
  drawerVisible.value = true;
};
</script>
