// packages/testground/src/demos/react/float.tsx
import { useState } from 'react';
import { Button, Float } from '@any-design/anyui-react';

export default function FloatDemo() {
  const [defaultVisible, setDefaultVisible] = useState(false);
  const [roundVisible, setRoundVisible] = useState(false);
  const [centeredVisible, setCenteredVisible] = useState(false);
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Float</div>
        <div className="demo-row">
          <Button type="primary" onClick={() => setDefaultVisible(true)}>
            Default
          </Button>
          <Button type="primary" onClick={() => setRoundVisible(true)}>
            Round
          </Button>
          <Button type="primary" onClick={() => setCenteredVisible(true)}>
            Centered
          </Button>
        </div>
      </div>
      <Float visible={defaultVisible} width={300} onUpdateVisible={setDefaultVisible}>
        <p>This is a float.</p>
      </Float>
      <Float visible={roundVisible} width={300} round onUpdateVisible={setRoundVisible}>
        <p>This is a round float.</p>
      </Float>
      <Float visible={centeredVisible} width={300} round centered onUpdateVisible={setCenteredVisible}>
        <p>This is a centered float.</p>
      </Float>
    </div>
  );
}

// packages/testground/src/demos/vue/float.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Variants</div>
      <div class="demo-row">
        <a-button type="primary" @click="floatVisible = true">Default</a-button>
        <a-button type="primary" @click="roundFloatVisible = true">Round</a-button>
        <a-button type="primary" @click="centeredFloatVisible = true">Centered</a-button>
        <a-float v-model:visible="floatVisible">
          <p>This is a float.</p>
        </a-float>
        <a-float v-model:visible="roundFloatVisible" round>
          <p>This is a float.</p>
        </a-float>
        <a-float v-model:visible="centeredFloatVisible" round centered>
          <p>This is a float.</p>
        </a-float>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const floatVisible = ref(false);
const roundFloatVisible = ref(false);
const centeredFloatVisible = ref(false);
</script>
