// packages/testground/src/demos/react/gradientText.tsx
import { GradientText } from '@any-design/anyui-react';

export default function GradientTextDemo() {
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Default</div>
        <div className="demo-row">
          <GradientText size="24px">Gradient Text</GradientText>
          <GradientText size="24px" reverseGradient>
            Reversed
          </GradientText>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Custom Gradient</div>
        <div className="demo-row">
          <GradientText size="24px" gradient="linear-gradient(90deg, #ff8a00, #e52e71)">
            Custom Gradient
          </GradientText>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Glow</div>
        <div className="demo-row">
          <GradientText size="24px" glow>
            Glowing Text
          </GradientText>
          <GradientText size="24px" glow reverseGradient>
            Reversed Glow
          </GradientText>
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/vue/gradientText.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Default</div>
      <div class="demo-row">
        <a-gradient-text size="24px">Default</a-gradient-text>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Glow</div>
      <div class="demo-row">
        <a-gradient-text size="24px" glow>Glowing Text</a-gradient-text>
        <a-gradient-text size="24px" glow reverse-gradient>Reversed Glow</a-gradient-text>
      </div>
    </div>
  </div>
</template>
