// packages/testground/src/demos/svelte/message.svelte
<script lang="ts">
  import { Button, Message, message } from '@any-design/anyui-svelte';
  import type { MessageType } from '@any-design/anyui-svelte';

  const popup = (type: MessageType) => {
    message({ type, content: `This is a ${type} message` });
  };

  const popupRound = () => {
    message({ type: 'info', content: 'Round message', round: true });
  };
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Popup Messages</div>
    <div class="demo-row">
      <Button size="small" onClick={() => popup('default')}>Default</Button>
      <Button size="small" onClick={() => popup('info')}>Info</Button>
      <Button size="small" onClick={() => popup('success')}>Success</Button>
      <Button size="small" onClick={() => popup('warning')}>Warning</Button>
      <Button size="small" onClick={() => popup('error')}>Error</Button>
      <Button size="small" onClick={popupRound}>Round</Button>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Inline Message Component</div>
    <div class="demo-col">
      <Message type="success" content="Success message" />
      <Message type="warning" content="Warning message" />
      <Message type="error" content="Error message" round />
    </div>
  </div>
</div>

// packages/testground/src/demos/vue/message.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Types</div>
      <div class="demo-row">
        <a-button @click="popup('default')">Default</a-button>
        <a-button @click="popup('info')">Info</a-button>
        <a-button @click="popup('success')">Success</a-button>
        <a-button @click="popup('warning')">Warning</a-button>
        <a-button @click="popup('error')">Error</a-button>
        <a-button @click="popupRound">Round</a-button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { message } from '@/packages/message';
import type { MessageType } from '@/packages/message/types';

const popup = (type: MessageType) => {
  message({
    type,
    content: type,
  });
};

const popupRound = () => {
  message({
    type: 'info',
    content: 'Round',
    round: true,
  });
};
</script>
