// packages/testground/src/demos/react/popper.tsx
import { Popper } from '@any-design/anyui-react';

const popupContent = (
  <span
    style={{
      display: 'inline-block',
      padding: '8px 12px',
      borderRadius: 8,
      background: 'var(--bg-light, #fff)',
      boxShadow: '0 2px 12px rgba(0, 0, 0, 0.15)',
    }}
  >
    popup
  </span>
);

export default function PopperDemo() {
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Hover (placements)</div>
        <div className="demo-row">
          <Popper popup={popupContent} placement="top">
            <span>top</span>
          </Popper>
          <Popper popup={popupContent} placement="bottom">
            <span>bottom</span>
          </Popper>
          <Popper popup={popupContent} placement="right">
            <span>right</span>
          </Popper>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Click Trigger</div>
        <div className="demo-row">
          <Popper popup={popupContent} triggerType="click" placement="bottom">
            <span>click me</span>
          </Popper>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Inset (no portal)</div>
        <div className="demo-row">
          <Popper popup={popupContent} placement="right" appendToBody={false}>
            <span>hover (inset)</span>
          </Popper>
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/vue/popper.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Inset</div>
      <div class="demo-row">
        <a-popper placement="right" :appendToBody="false">
          <template #popup>
            <span>popup</span>
          </template>
          <span>trigger</span>
        </a-popper>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">With Transition</div>
      <div class="demo-row">
        <a-popper placement="right" transition="fade">
          <template #popup>
            <span>popup</span>
          </template>
          <span>trigger (transition)</span>
        </a-popper>
      </div>
    </div>
  </div>
</template>

<style>
.fade-enter-active,
.fade-leave-active {
  transition: all var(--anim-duration, 200ms) ease;
}
.fade-enter-to {
  top: 0 !important;
  opacity: 1;
}
.fade-enter-from,
.fade-leave-to {
  top: -4px !important;
  opacity: 0;
}
</style>
