// packages/testground/src/demos/svelte/qrCode.svelte
<script lang="ts">
  import { QrCode } from '@any-design/anyui-svelte';
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Basic</div>
    <div class="demo-row">
      <QrCode value="https://anyui.dev" />
      <QrCode value="AnyUI QR code" size={120} margin={1} />
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Custom color</div>
    <div class="demo-row">
      <QrCode
        value="anyui:qrcode"
        size={152}
        errorCorrectionLevel="H"
        dark="#0f172a"
        light="#f8fafc"
      />
      <QrCode value="" placeholder="Set a value" bordered={false} />
    </div>
  </div>
</div>

// packages/testground/src/demos/vue/qrCode.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Basic</div>
      <div class="demo-row">
        <a-qr-code value="https://anyui.dev" />
        <a-qr-code value="AnyUI QR code" :size="120" :margin="1" />
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Custom color</div>
      <div class="demo-row">
        <a-qr-code
          value="anyui:qrcode"
          :size="152"
          error-correction-level="H"
          dark="#0f172a"
          light="#f8fafc"
        />
        <a-qr-code value="" placeholder="Set a value" :bordered="false" />
      </div>
    </div>
  </div>
</template>
