// packages/testground/src/demos/react/radioButtonGroup.tsx
import { useState } from 'react';
import { RadioButtonGroup } from '@any-design/anyui-react';

const items = [
  { label: 'Button 1', value: 1 },
  { label: 'Button 2', value: 2 },
  { label: 'Button 3', value: 3 },
];

export default function RadioButtonGroupDemo() {
  const [selected, setSelected] = useState<string | number>(1);
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Default</div>
        <div className="demo-col">
          <RadioButtonGroup items={items} modelValue={selected} onUpdateModelValue={setSelected} />
          <span>Selected: {selected}</span>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Round</div>
        <div className="demo-row">
          <RadioButtonGroup items={items} round />
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Sizes</div>
        <div className="demo-row">
          <RadioButtonGroup items={items} size="small" />
          <RadioButtonGroup items={items} />
          <RadioButtonGroup items={items} size="large" />
        </div>
      </div>
    </div>
  );
}

// packages/testground/src/demos/vue/radioButtonGroup.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Default &amp; Round</div>
      <div class="demo-row">
        <a-radio-button-group :items="items"></a-radio-button-group>
        <a-radio-button-group :items="items" round></a-radio-button-group>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Sizes</div>
      <div class="demo-row">
        <a-radio-button-group :items="items" size="small"></a-radio-button-group>
        <a-radio-button-group :items="items"></a-radio-button-group>
        <a-radio-button-group :items="items" size="large"></a-radio-button-group>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const items = [
  {
    label: 'Button 1',
    value: 1,
  },
  {
    label: 'Button 2',
    value: 2,
  },
  {
    label: 'Button 3',
    value: 3,
  },
];
</script>
