// packages/testground/src/demos/svelte/select.svelte
<script lang="ts">
  import { Select } from '@any-design/anyui-svelte';
  import type { ASelectItems } from '@any-design/anyui-svelte';

  const items: ASelectItems = Array.from({ length: 6 }, (_, index) => ({
    text: `Item ${index}`,
    value: index,
  }));

  let value: string | number | null | undefined = $state('');
  let multiValue: (string | number)[] = $state([]);
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Basic</div>
    <div class="demo-col">
      <Select {items} bind:modelValue={value} placeholder="Select an item" />
      <span>Selected: {value === '' ? '(none)' : value}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Multiple</div>
    <div class="demo-col">
      <Select {items} bind:modelValue={multiValue} multiple placeholder="Select items" />
      <span>Selected: {multiValue.length ? multiValue.join(', ') : '(none)'}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Variants</div>
    <div class="demo-col">
      <Select {items} round placeholder="Round" />
      <Select {items} size="large" placeholder="Large" />
      <Select {items} disabled placeholder="Disabled" />
    </div>
  </div>
</div>

// packages/testground/src/demos/vue/select.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Basic</div>
      <div class="demo-col">
        <a-select v-model="value" :items="items" placeholder="Select an item"></a-select>
        <span>Selected: {{ value === '' ? '(none)' : value }}</span>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Multiple</div>
      <div class="demo-col">
        <a-select v-model="multiValue" :items="items" multiple placeholder="Select items"></a-select>
        <span>Selected: {{ multiValue.length ? multiValue.join(', ') : '(none)' }}</span>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Variants</div>
      <div class="demo-col">
        <a-select :items="items" round placeholder="Round"></a-select>
        <a-select :items="items" size="large" placeholder="Large"></a-select>
        <a-select :items="items" disabled placeholder="Disabled"></a-select>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const items = new Array(6).fill(0).map((_, index) => ({
  text: `Item ${index}`,
  value: index,
}));

const value = ref<string | number>('');
const multiValue = ref<(string | number)[]>([]);
</script>
