// packages/testground/src/demos/vue/tag.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Sizes</div>
      <div class="demo-row">
        <a-tag size="small">small</a-tag>
        <a-tag>default</a-tag>
        <a-tag size="large">large</a-tag>
      </div>
    </div>
    <div class="demo-block">
      <div class="demo-block__label">Round &amp; Custom Color</div>
      <div class="demo-row">
        <a-tag round>round</a-tag>
        <a-tag color="#1faeff">custom color</a-tag>
        <a-tag round color="#e52e71" bgColor="#ffe2ec">custom bg</a-tag>
      </div>
    </div>
  </div>
</template>

// packages/svelte/src/components/Tag.svelte
<script lang="ts">
  export let round = false;
  export let size = 'default';
  export let color = '';
  export let bgColor = '';
  export let className = '';
  export { className as class };
</script>

<div class="a-tag a-tag--{size} {round ? 'a-tag--round' : ''} {(color || bgColor) ? 'a-tag--custom-color' : ''} {className}" style:color={color || undefined} style:background-color={bgColor || color || undefined}>
  <slot />
</div>
