// src/testground/sections/card.vue
<template>
  <div class="testground-content__item">
    <p class="testground-content-title">Card</p>
    <div class="testground-flex">
      <a-card>
        <p>No Header</p>
      </a-card>
      <a-card title="Title">
        <p>With header</p>
      </a-card>
      <a-card>
        <p>With footer</p>
        <template #footer>
          <p>This is a footer</p>
        </template>
      </a-card>
      <a-card title="Title">
        <p>With header and footer</p>
        <template #footer>
          <p>This is a footer</p>
        </template>
      </a-card>
      <a-card clean>
        <p>This is a clean card</p>
        <template #footer>
          <p>This is a footer</p>
        </template>
      </a-card>
    </div>
  </div>
</template>

// packages/testground/src/demos/react/card.tsx
import { Card } from '@any-design/anyui-react';

export default function CardDemo() {
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Basic</div>
        <div className="demo-row">
          <Card width={180}>
            <p>No header</p>
          </Card>
          <Card width={180} title="Title">
            <p>With header</p>
          </Card>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Footer</div>
        <div className="demo-row">
          <Card width={180} footer={<p>This is a footer</p>}>
            <p>With footer</p>
          </Card>
          <Card width={180} title="Title" footer={<p>This is a footer</p>}>
            <p>Header and footer</p>
          </Card>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Clean</div>
        <div className="demo-row">
          <Card width={180} clean footer={<p>This is a footer</p>}>
            <p>This is a clean card</p>
          </Card>
        </div>
      </div>
    </div>
  );
}
