// packages/testground/src/demos/svelte/image.svelte
<script lang="ts">
  import { Image } from '@any-design/anyui-svelte';
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Basic</div>
    <div class="demo-row">
      <Image src="https://picsum.photos/seed/anyui/300/200" width={160} height={100} />
      <Image
        src="https://picsum.photos/seed/anyui/300/200"
        width={160}
        height={100}
        size="contain"
      />
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">States</div>
    <div class="demo-row">
      <Image width={160} height={100} loading="Loading..." />
      <Image width={160} height={100} error="Failed to load" />
    </div>
  </div>
</div>

// packages/testground/src/demos/react/image.tsx
import { Image } from '@any-design/anyui-react';

export default function ImageDemo() {
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Basic</div>
        <div className="demo-row">
          <Image src="https://picsum.photos/seed/anyui/300/200" width={180} height={120} />
          <Image src="https://picsum.photos/seed/anyui2/300/200" width={120} height={120} size="contain" />
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Error Fallback</div>
        <div className="demo-row">
          <Image width={180} height={80} error={<span>Failed to load</span>} />
        </div>
      </div>
    </div>
  );
}
