// packages/testground/src/demos/svelte/layout.svelte
<script lang="ts">
  import { Content, Footer, Header, Layout, Side } from '@any-design/anyui-svelte';
</script>

<div class="layout-demo">
  <div class="demo-block">
    <div class="demo-block__label">Side + Header / Content / Footer</div>
    <div class="demo-row" style="height: 240px;">
      <Layout hasSide>
        <Side width={90}>Side</Side>
        <Layout direction="vertical">
          <Header height={48}>Header</Header>
          <Content>Content</Content>
          <Footer height={40}>Footer</Footer>
        </Layout>
      </Layout>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Vertical Only</div>
    <div class="demo-row" style="height: 200px;">
      <Layout direction="vertical">
        <Header height={48}>Header</Header>
        <Content>Content</Content>
      </Layout>
    </div>
  </div>
</div>

<style>
  .layout-demo :global(.a-layout) {
    width: 100%;
    height: 100%;
  }
  .layout-demo :global(.a-layout-inner) {
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: var(--primary, #7388e6);
    color: var(--text-btn, #fff);
  }
  .layout-demo :global(.a-side) {
    background-color: var(--bg-light, #f3f4fa);
    color: var(--primary, #7388e6);
  }
  .layout-demo :global(.a-content) {
    background-color: var(--primary-80, rgba(115, 136, 230, 0.8));
  }
</style>

// packages/testground/src/demos/react/layout.tsx
import { Content, Footer, Header, Layout, Side } from '@any-design/anyui-react';
import type { CSSProperties } from 'react';

const cellStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  background: 'var(--primary)',
  color: 'var(--text-btn)',
};

const sideStyle: CSSProperties = {
  ...cellStyle,
  background: 'var(--bg-light)',
  color: 'var(--primary)',
};

const contentInnerStyle: CSSProperties = {
  ...cellStyle,
  background: 'var(--primary-80)',
  width: '100%',
  height: '100%',
};

const ContentInner = () => <div style={contentInnerStyle}>Content</div>;

export default function LayoutDemo() {
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Side + Header / Content / Footer</div>
        <div style={{ height: 240 }}>
          <Layout hasSide>
            <Side width={100} style={sideStyle}>
              Side
            </Side>
            <Layout>
              <Header height={48} style={cellStyle}>
                Header
              </Header>
              <Content>
                <ContentInner />
              </Content>
              <Footer height={48} style={cellStyle}>
                Footer
              </Footer>
            </Layout>
          </Layout>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Side On The Right</div>
        <div style={{ height: 180 }}>
          <Layout hasSide>
            <Layout>
              <Content>
                <ContentInner />
              </Content>
              <Footer height={48} style={cellStyle}>
                Footer
              </Footer>
            </Layout>
            <Side width={100} style={sideStyle}>
              Side
            </Side>
          </Layout>
        </div>
      </div>
    </div>
  );
}
