// packages/testground/src/demos/vue/listView.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Types</div>
      <div class="demo-col">
        <div class="list-view-wrapper">
          <a-list-view item-height="54px">
            <a-list-view-item label="Avatar"
              ><a-button type="primary">View</a-button></a-list-view-item
            >
            <a-list-view-item label="Nickname"><span>AnyUI</span></a-list-view-item>
            <a-list-view-item label="Email"><span>anyui@pwp.sh</span></a-list-view-item>
          </a-list-view>
        </div>
        <div class="list-view-wrapper">
          <a-list-view item-height="54px" type="bordered">
            <a-list-view-item label="Avatar"
              ><a-button type="primary">View</a-button></a-list-view-item
            >
            <a-list-view-item label="Nickname"><span>AnyUI</span></a-list-view-item>
            <a-list-view-item label="Email"><span>anyui@pwp.sh</span></a-list-view-item>
          </a-list-view>
        </div>
        <div class="list-view-wrapper">
          <a-list-view item-height="64px" type="deep">
            <a-list-view-item label="Avatar"
              ><a-button type="primary">View</a-button></a-list-view-item
            >
            <a-list-view-item label="Nickname"><span>AnyUI</span></a-list-view-item>
            <a-list-view-item label="Email"><span>anyui@pwp.sh</span></a-list-view-item>
          </a-list-view>
        </div>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.list-view-wrapper {
  position: relative;
  width: 100%;
  height: 200px;
}
</style>

// packages/testground/src/demos/react/listView.tsx
import { Button, ListView, ListViewItem } from '@any-design/anyui-react';

const rows = (
  <>
    <ListViewItem label="Avatar">
      <Button type="primary" size="small">
        View
      </Button>
    </ListViewItem>
    <ListViewItem label="Nickname">
      <span>AnyUI</span>
    </ListViewItem>
    <ListViewItem label="Email">
      <span>anyui@pwp.sh</span>
    </ListViewItem>
  </>
);

export default function ListViewDemo() {
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Borderless (default)</div>
        <ListView itemHeight="54px">{rows}</ListView>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Bordered</div>
        <ListView itemHeight="54px" type="bordered">
          {rows}
        </ListView>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Deep</div>
        <ListView itemHeight="64px" type="deep">
          {rows}
        </ListView>
      </div>
    </div>
  );
}
