// packages/testground/src/demos/svelte/pagination.svelte
<script lang="ts">
  import { Pagination } from '@any-design/anyui-svelte';
  import type { PaginationMeta } from '@any-design/anyui-svelte';

  let pagination: PaginationMeta = $state({ current: 1, pageSize: 10, total: 50 });
  let largePagination: PaginationMeta = $state({ current: 3, pageSize: 10, total: 80 });
  let shapesPagination: PaginationMeta = $state({ current: 3, pageSize: 10, total: 200 });
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Basic</div>
    <div class="demo-col">
      <Pagination bind:pagination />
      <span>Current page: {pagination.current}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">More Pages</div>
    <div class="demo-col">
      <Pagination bind:pagination={largePagination} />
      <span>Current page: {largePagination.current}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Shapes</div>
    <div class="demo-col">
      <Pagination bind:pagination={shapesPagination} shape="rounded" />
      <Pagination bind:pagination={shapesPagination} shape="squircle" />
      <Pagination bind:pagination={shapesPagination} shape="circle" />
    </div>
  </div>
</div>

// packages/testground/src/demos/react/pagination.tsx
import { useState } from 'react';
import { Pagination } from '@any-design/anyui-react';
import type { PaginationMeta } from '@any-design/anyui-react';

export default function PaginationDemo() {
  const [pagination, setPagination] = useState<PaginationMeta>({ current: 1, pageSize: 10, total: 100 });
  const [largePagination, setLargePagination] = useState<PaginationMeta>({ current: 1, pageSize: 10, total: 60 });
  const [shapesPagination, setShapesPagination] = useState<PaginationMeta>({ current: 3, pageSize: 10, total: 200 });
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Basic</div>
        <div className="demo-col">
          <Pagination pagination={pagination} onUpdatePagination={setPagination} />
          <span>Current page: {pagination.current}</span>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Fewer Pages</div>
        <div className="demo-col">
          <Pagination pagination={largePagination} onUpdatePagination={setLargePagination} />
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Shapes</div>
        <div className="demo-col">
          <Pagination pagination={shapesPagination} shape="rounded" onUpdatePagination={setShapesPagination} />
          <Pagination pagination={shapesPagination} shape="squircle" onUpdatePagination={setShapesPagination} />
          <Pagination pagination={shapesPagination} shape="circle" onUpdatePagination={setShapesPagination} />
        </div>
      </div>
    </div>
  );
}
