// packages/testground/src/demos/svelte/popupMenu.svelte
<script lang="ts">
  import { PopupMenu } from '@any-design/anyui-svelte';

  const items = ['Item 1', 'Item 2', 'Item 3', 'Item 4'];

  let lastCommand = $state('');

  const onCommand = (command: string) => {
    lastCommand = command;
  };
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Trigger Types</div>
    <div class="demo-row">
      <PopupMenu {items} {onCommand}>
        <span class="popup-menu-trigger">hover</span>
      </PopupMenu>
      <PopupMenu {items} triggerType="click" hideAfterClick {onCommand}>
        <span class="popup-menu-trigger">click</span>
      </PopupMenu>
      <PopupMenu {items} triggerType="contextmenu" hideAfterClick {onCommand}>
        <span class="popup-menu-trigger">contextmenu</span>
      </PopupMenu>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Grouped (only one opens)</div>
    <div class="demo-row">
      <PopupMenu {items} group="demo" triggerType="click" hideAfterClick {onCommand}>
        <span class="popup-menu-trigger">grouped A</span>
      </PopupMenu>
      <PopupMenu {items} group="demo" triggerType="click" hideAfterClick {onCommand}>
        <span class="popup-menu-trigger">grouped B</span>
      </PopupMenu>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Command Event</div>
    <div class="demo-row">
      <span>Last command: {lastCommand || 'none'}</span>
    </div>
  </div>
</div>

<style>
  .popup-menu-trigger {
    cursor: pointer;
    text-decoration: underline;
  }
</style>

// packages/testground/src/demos/react/popupMenu.tsx
import { useState } from 'react';
import { PopupMenu } from '@any-design/anyui-react';

const items = ['Item 1', 'Item 2', 'Item 3', 'Item 4'];

export default function PopupMenuDemo() {
  const [lastCommand, setLastCommand] = useState('');
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Triggers</div>
        <div className="demo-row">
          <PopupMenu items={items} onCommand={(command: string) => setLastCommand(command)}>
            <span>hover</span>
          </PopupMenu>
          <PopupMenu items={items} triggerType="click" hideAfterClick onCommand={(command: string) => setLastCommand(command)}>
            <span>click</span>
          </PopupMenu>
          <PopupMenu items={items} triggerType="contextmenu" hideAfterClick onCommand={(command: string) => setLastCommand(command)}>
            <span>contextmenu</span>
          </PopupMenu>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Grouped (only one open)</div>
        <div className="demo-row">
          <PopupMenu group="demo" items={items} triggerType="click" hideAfterClick>
            <span>grouped A</span>
          </PopupMenu>
          <PopupMenu group="demo" items={items} triggerType="click" hideAfterClick>
            <span>grouped B</span>
          </PopupMenu>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Last Command</div>
        <div className="demo-row">
          <span>{lastCommand || '(none)'}</span>
        </div>
      </div>
    </div>
  );
}
