// packages/testground/src/demos/svelte/radioButtonGroup.svelte
<script lang="ts">
  import { RadioButtonGroup } from '@any-design/anyui-svelte';
  import type { ARadioGroupItems } from '@any-design/anyui-svelte';

  const items: ARadioGroupItems = [
    { label: 'Button 1', value: 1 },
    { label: 'Button 2', value: 2 },
    { label: 'Button 3', value: 3 },
  ];

  let value: string | number | undefined = $state(1);
  let roundValue: string | number | undefined = $state(2);
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Default</div>
    <div class="demo-col">
      <RadioButtonGroup {items} bind:modelValue={value} />
      <span>Selected: {value ?? 'none'}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Round</div>
    <div class="demo-col">
      <RadioButtonGroup {items} round bind:modelValue={roundValue} />
      <span>Selected: {roundValue ?? 'none'}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Sizes</div>
    <div class="demo-row">
      <RadioButtonGroup {items} size="small" />
      <RadioButtonGroup {items} />
      <RadioButtonGroup {items} size="large" />
    </div>
  </div>
</div>

// packages/testground/src/demos/react/radioButtonGroup.tsx
import { useState } from 'react';
import { RadioButtonGroup } from '@any-design/anyui-react';

const items = [
  { label: 'Button 1', value: 1 },
  { label: 'Button 2', value: 2 },
  { label: 'Button 3', value: 3 },
];

export default function RadioButtonGroupDemo() {
  const [selected, setSelected] = useState<string | number>(1);
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Default</div>
        <div className="demo-col">
          <RadioButtonGroup items={items} modelValue={selected} onUpdateModelValue={setSelected} />
          <span>Selected: {selected}</span>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Round</div>
        <div className="demo-row">
          <RadioButtonGroup items={items} round />
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Sizes</div>
        <div className="demo-row">
          <RadioButtonGroup items={items} size="small" />
          <RadioButtonGroup items={items} />
          <RadioButtonGroup items={items} size="large" />
        </div>
      </div>
    </div>
  );
}
