// packages/testground/src/demos/svelte/switch.svelte
<script lang="ts">
  import { Switch } from '@any-design/anyui-svelte';

  let enabled = $state(true);
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Switch</div>
    <div class="demo-row">
      <Switch bind:modelValue={enabled} />
      <span>Enabled: {enabled}</span>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Disabled</div>
    <div class="demo-row">
      <Switch modelValue={true} disabled />
    </div>
  </div>
</div>

// packages/testground/src/demos/react/switch.tsx
import { useState } from 'react';
import { Switch } from '@any-design/anyui-react';

export default function SwitchDemo() {
  const [enabled, setEnabled] = useState(true);

  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Switch</div>
        <div className="demo-row">
          <Switch modelValue={enabled} onUpdateModelValue={setEnabled} />
          <span>Enabled: {String(enabled)}</span>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Disabled</div>
        <div className="demo-row">
          <Switch modelValue disabled />
        </div>
      </div>
    </div>
  );
}
