// packages/testground/src/demos/vue/textarea.vue
<template>
  <div>
    <div class="demo-block">
      <div class="demo-block__label">Variants</div>
      <div class="demo-col">
        <a-textarea placeholder="This is a textarea..."></a-textarea>
        <a-textarea
          placeholder="This is a textarea..."
          :minRows="1"
          :maxRows="6"
          disableResizeCorner
        ></a-textarea>
        <a-textarea placeholder="This is a textarea..." borderless></a-textarea>
        <a-textarea
          placeholder="This is a textarea..."
          :minRows="1"
          :maxRows="6"
          disableResizeCorner
          autoMatchHeight
          borderless
        ></a-textarea>
      </div>
    </div>
  </div>
</template>

// packages/testground/src/demos/react/textarea.tsx
import { useState } from 'react';
import { Textarea } from '@any-design/anyui-react';

export default function TextareaDemo() {
  const [value, setValue] = useState('');
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Variants</div>
        <div className="demo-col">
          <Textarea placeholder="This is a textarea..." />
          <Textarea placeholder="Borderless textarea..." borderless />
          <Textarea placeholder="Fixed height" height={80} disableResizeCorner />
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Controlled</div>
        <div className="demo-col">
          <Textarea placeholder="Type something..." modelValue={value} onUpdateModelValue={setValue} />
          <span>Length: {value.length}</span>
        </div>
      </div>
    </div>
  );
}
