// packages/testground/src/demos/svelte/textarea.svelte
<script lang="ts">
  import { Textarea } from '@any-design/anyui-svelte';

  let text = $state('');

  const onInput = (event: Event) => {
    const target = event.target as HTMLTextAreaElement | null;
    text = target ? target.value : '';
  };
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Variants</div>
    <div class="demo-col">
      <Textarea placeholder="Default" height={72} />
      <Textarea placeholder="Borderless" borderless height={72} />
      <Textarea placeholder="Resizable" resizable height={72} />
      <Textarea placeholder="Disabled" disabled height={72} />
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Events</div>
    <div class="demo-col">
      <Textarea placeholder="Type something..." height={72} maxlength={120} {onInput} />
      <span>Length: {text.length}</span>
    </div>
  </div>
</div>

// packages/testground/src/demos/react/textarea.tsx
import { useState } from 'react';
import { Textarea } from '@any-design/anyui-react';

export default function TextareaDemo() {
  const [value, setValue] = useState('');
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Variants</div>
        <div className="demo-col">
          <Textarea placeholder="This is a textarea..." />
          <Textarea placeholder="Borderless textarea..." borderless />
          <Textarea placeholder="Fixed height" height={80} disableResizeCorner />
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Controlled</div>
        <div className="demo-col">
          <Textarea placeholder="Type something..." modelValue={value} onUpdateModelValue={setValue} />
          <span>Length: {value.length}</span>
        </div>
      </div>
    </div>
  );
}
