// packages/testground/src/demos/svelte/upload.svelte
<script lang="ts">
  import { Button, Upload } from '@any-design/anyui-svelte';

  let status = $state('default');
  let lastFile = $state('');

  const onUpload = (file: File) => {
    lastFile = file?.name ?? '';
  };
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Status</div>
    <div class="demo-row">
      <Button round size="small" onClick={() => (status = 'default')}>Default</Button>
      <Button round size="small" onClick={() => (status = 'uploading')}>Uploading</Button>
      <Button round size="small" onClick={() => (status = 'error')}>Error</Button>
      <Button round size="small" onClick={() => (status = 'success')}>Success</Button>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Upload Area</div>
    <div class="demo-col">
      <div style="width: 200px; height: 160px;">
        <Upload {status} {onUpload}>
          <span>Click or drop a file</span>
          {#snippet dragging()}
            <span>Drop it!</span>
          {/snippet}
          {#snippet uploading()}
            <span>Uploading...</span>
          {/snippet}
          {#snippet error()}
            <span>Upload failed</span>
          {/snippet}
          {#snippet success()}
            <span>Uploaded</span>
          {/snippet}
        </Upload>
      </div>
      <span>Last file: {lastFile || 'none'}</span>
    </div>
  </div>
</div>

// packages/testground/src/demos/react/upload.tsx
import { useState } from 'react';
import { Button, Upload } from '@any-design/anyui-react';
import type { UploadStatus } from '@any-design/anyui-react';

const statuses: UploadStatus[] = ['default', 'uploading', 'error', 'success'];

export default function UploadDemo() {
  const [status, setStatus] = useState<UploadStatus>('default');
  const [fileName, setFileName] = useState('');
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Status</div>
        <div className="demo-row">
          {statuses.map((item) => (
            <Button key={item} round size="small" onClick={() => setStatus(item)}>
              {item}
            </Button>
          ))}
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Upload Area</div>
        <div className="demo-col">
          <div style={{ width: 200, height: 160 }}>
            <Upload
              status={status}
              dragging={<span>Dragging</span>}
              uploading={<span>Uploading</span>}
              error={<span>Error</span>}
              success={<span>Success</span>}
              onUpload={(file: File) => setFileName(file.name)}
            >
              <span>Click or drop a file</span>
            </Upload>
          </div>
          <span>Last file: {fileName || '(none)'}</span>
        </div>
      </div>
    </div>
  );
}
