// packages/testground/src/demos/react/collapse.tsx
import { useState } from 'react';
import { Button, Collapse } from '@any-design/anyui-react';

export default function CollapseDemo() {
  const [verticalVisible, setVerticalVisible] = useState(false);
  const [horizontalVisible, setHorizontalVisible] = useState(false);
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Vertical</div>
        <div className="demo-col">
          <div className="demo-row">
            <Button onClick={() => setVerticalVisible((value) => !value)}>Toggle Vertical</Button>
          </div>
          <Collapse visible={verticalVisible}>
            {Array.from({ length: 5 }, (_, index) => (
              <p key={index}>vertical content {index + 1}</p>
            ))}
          </Collapse>
        </div>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Horizontal</div>
        <div className="demo-col">
          <div className="demo-row">
            <Button onClick={() => setHorizontalVisible((value) => !value)}>Toggle Horizontal</Button>
          </div>
          <Collapse direction="horizontal" visible={horizontalVisible}>
            {Array.from({ length: 5 }, (_, index) => (
              <span key={index} style={{ marginRight: 8 }}>
                horizontal
              </span>
            ))}
          </Collapse>
        </div>
      </div>
    </div>
  );
}

// packages/vue/src/testground/sections/collapse.vue
<template>
  <div class="testground-content__item">
    <p class="testground-content-title">Collapse</p>
    <div class="testground-flex">
      <a-button @click="handleClick('vertical')">Vertical</a-button>
      <a-collapse :visible="verticalVisible">
        <p v-for="(_, idx) in new Array(10).fill(0)" :key="idx">vertical</p>
      </a-collapse>
      <a-button @click="handleClick('horizontal')">Horizontal</a-button>
      <a-collapse direction="horizontal" :visible="horizontalVisible">
        <span v-for="(_, idx) in new Array(10).fill(0)" :key="idx">horizontal</span>
      </a-collapse>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  data() {
    return {
      verticalVisible: false,
      horizontalVisible: false,
    };
  },
  methods: {
    handleClick(direction: 'horizontal' | 'vertical') {
      this[`${direction}Visible`] = !this[`${direction}Visible`];
    },
  },
});
</script>
