// packages/testground/src/demos/svelte/upload.svelte
<script lang="ts">
  import { Button, Upload } from '@any-design/anyui-svelte';

  let status = $state('default');
  let lastFile = $state('');

  const onUpload = (file: File) => {
    lastFile = file?.name ?? '';
  };
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Status</div>
    <div class="demo-row">
      <Button round size="small" onClick={() => (status = 'default')}>Default</Button>
      <Button round size="small" onClick={() => (status = 'uploading')}>Uploading</Button>
      <Button round size="small" onClick={() => (status = 'error')}>Error</Button>
      <Button round size="small" onClick={() => (status = 'success')}>Success</Button>
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Upload Area</div>
    <div class="demo-col">
      <div style="width: 200px; height: 160px;">
        <Upload {status} {onUpload}>
          <span>Click or drop a file</span>
          {#snippet dragging()}
            <span>Drop it!</span>
          {/snippet}
          {#snippet uploading()}
            <span>Uploading...</span>
          {/snippet}
          {#snippet error()}
            <span>Upload failed</span>
          {/snippet}
          {#snippet success()}
            <span>Uploaded</span>
          {/snippet}
        </Upload>
      </div>
      <span>Last file: {lastFile || 'none'}</span>
    </div>
  </div>
</div>

// packages/vue/src/testground/sections/upload.vue
<template>
  <div class="testground-content__item">
    <p class="testground-content-title">Upload</p>
    <div style="display: flex; margin-bottom: 20px">
      <a-button
        round
        size="small"
        style="margin-right: 8px"
        @click="updateUploadStatus('uploading')"
      >Uploading</a-button>
      <a-button
        round
        size="small"
        style="margin-right: 8px"
        @click="updateUploadStatus('error')"
      >Error</a-button>
      <a-button
        round
        size="small"
        style="margin-right: 8px"
        @click="updateUploadStatus('success')"
      >Success</a-button>
    </div>
    <div style="width: 200px; height: 200px">
      <a-upload :status="uploadStatus">
        <span>Default</span>
        <template #dragging>
          <span>Dragging</span>
        </template>
        <template #uploading>
          <span>Uploading</span>
        </template>
        <template #error>
          <span>Error</span>
        </template>
        <template #success>
          <span>Success</span>
        </template>
      </a-upload>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
  setup() {
    const uploadStatus = ref('');
    const updateUploadStatus = (status: string) => {
      uploadStatus.value = status;
    };
    return {
      uploadStatus,
      updateUploadStatus,
    };
  },
});
</script>
