// packages/testground/src/demos/svelte/avatar.svelte
<script lang="ts">
  import { Avatar } from '@any-design/anyui-svelte';

  const src = 'https://0.gravatar.com/avatar/';
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Sizes</div>
    <div class="demo-row">
      <Avatar {src} size="xlarge" />
      <Avatar {src} size="large" />
      <Avatar {src} size="medium" />
      <Avatar {src} size="small" />
      <Avatar {src} size="xsmall" />
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Round &amp; Custom Width</div>
    <div class="demo-row">
      <Avatar {src} size="large" round />
      <Avatar {src} width={40} />
      <Avatar {src} width="56px" round />
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">Fallback</div>
    <div class="demo-row">
      <Avatar size="large" round>AU</Avatar>
      <Avatar size="large" fallback="A" />
    </div>
  </div>
</div>

// src/testground/sections/avatar.vue
<template>
  <div class="testground-content__item">
    <p class="testground-content-title">Avatar</p>
    <div class="container">
      <a-avatar src="https://0.gravatar.com/avatar/" size="xlarge" round />
      <a-avatar src="https://0.gravatar.com/avatar/" size="large" />
      <a-avatar src="https://0.gravatar.com/avatar/" size="medium" :width="40" />
      <a-avatar src="https://0.gravatar.com/avatar/" size="small" width="50px" round />
      <a-avatar src="https://0.gravatar.com/avatar/" size="xsmall" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { Avatar as AAvatar } from '../../';
</script>

<style lang="scss" scoped>
.container {
  display: flex;
  gap: 12px;
  align-items: center;
}
</style>
