// packages/testground/src/demos/react/form.tsx
import { useRef, useState } from 'react';
import { Button, Form, FormItem, Input } from '@any-design/anyui-react';

const rules = {
  text: [{ required: true, message: 'Please input text' }],
};

const inlineRules = {
  text1: [{ required: true, message: 'Please input text' }],
  text2: [{ required: true, message: 'Please input text' }],
};

export default function FormDemo() {
  const formRef = useRef<any>(null);
  const inlineFormRef = useRef<any>(null);
  const [formData, setFormData] = useState({ text: '' });
  const [inlineFormData, setInlineFormData] = useState({ text1: '', text2: '' });
  return (
    <div>
      <div className="demo-block">
        <div className="demo-block__label">Basic Form</div>
        <Form ref={formRef} modelValue={formData} rules={rules}>
          <FormItem prop="text" label="Label">
            <Input
              modelValue={formData.text}
              onUpdateModelValue={(text: string) => setFormData({ text })}
            />
          </FormItem>
          <FormItem>
            <Button type="primary" onClick={() => formRef.current?.validate()}>
              Submit
            </Button>
          </FormItem>
        </Form>
      </div>
      <div className="demo-block">
        <div className="demo-block__label">Inline Form</div>
        <Form ref={inlineFormRef} modelValue={inlineFormData} rules={inlineRules} layout="inline">
          <FormItem prop="text1" label="Label">
            <Input
              modelValue={inlineFormData.text1}
              onUpdateModelValue={(text1: string) => setInlineFormData((current) => ({ ...current, text1 }))}
            />
          </FormItem>
          <FormItem prop="text2" label="Label">
            <Input
              modelValue={inlineFormData.text2}
              onUpdateModelValue={(text2: string) => setInlineFormData((current) => ({ ...current, text2 }))}
            />
          </FormItem>
          <FormItem>
            <Button
              type="primary"
              fill
              onClick={() => {
                setInlineFormData({ text1: '', text2: '' });
                inlineFormRef.current?.clearFields();
              }}
            >
              Clear
            </Button>
          </FormItem>
        </Form>
      </div>
    </div>
  );
}

// src/testground/sections/form.vue
<template>
  <div class="testground-content__item">
    <p class="testground-content-title">Form</p>
    <div class="testground-flex">
      <a-form ref="form" v-model="formData" :rules="rules">
        <a-form-item prop="text" label="Label">
          <a-input v-model="formData.text"></a-input>
        </a-form-item>
        <a-form-item>
          <a-button type="primary" @click="submit">Submit</a-button>
        </a-form-item>
      </a-form>
      <a-form ref="inlineForm" v-model="inlineFormData" layout="inline" :rules="rules">
        <a-form-item prop="text1" label="Label">
          <a-input v-model="inlineFormData.text1"></a-input>
        </a-form-item>
        <a-form-item prop="text2" label="Label">
          <a-input v-model="inlineFormData.text2"></a-input>
        </a-form-item>
        <a-form-item>
          <a-button type="primary" fill @click="clear">Clear</a-button>
        </a-form-item>
      </a-form>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import type { Form } from '../../index';

export default defineComponent({
  data() {
    return {
      formData: {
        text: '',
      },
      inlineFormData: {
        text1: '',
        text2: '',
      },
      rules: {
        text: [
          {
            required: true,
            message: 'Please input text',
          },
        ],
      },
    };
  },
  methods: {
    submit() {
      (this.$refs.form as InstanceType<typeof Form> | undefined)?.validate();
    },
    clear() {
      (this.$refs.inlineForm as InstanceType<typeof Form> | undefined)?.clearFields();
    },
  },
});
</script>
