// packages/testground/src/demos/svelte/image.svelte
<script lang="ts">
  import { Image } from '@any-design/anyui-svelte';
</script>

<div>
  <div class="demo-block">
    <div class="demo-block__label">Basic</div>
    <div class="demo-row">
      <Image src="https://picsum.photos/seed/anyui/300/200" width={160} height={100} />
      <Image
        src="https://picsum.photos/seed/anyui/300/200"
        width={160}
        height={100}
        size="contain"
      />
    </div>
  </div>
  <div class="demo-block">
    <div class="demo-block__label">States</div>
    <div class="demo-row">
      <Image width={160} height={100} loading="Loading..." />
      <Image width={160} height={100} error="Failed to load" />
    </div>
  </div>
</div>

// src/testground/sections/image.vue
<template>
  <div class="testground-content__item">
    <p class="testground-content-title">Image</p>
    <div class="testground-flex">
      <a-image
        src="https://github.com/any-design/anyui/blob/main/public/favicon.png?raw=true"
        width="200"
        height="200"
      >
        <template v-slot:loading><span>Loading</span></template>
        <template v-slot:error><span>Error</span></template>
      </a-image>
    </div>
  </div>
</template>
